spring:
  application:
    name: hellospringhomework2
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: SPRING_HOMEWORK
    password: 1234
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/ktdsuniversity/edu/hellospringhomework2/**/dao/mapper/*Mapper.xml